name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: fix nuget problems
      run: dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org --configfile $env:APPDATA\NuGet\NuGet.Config
      
    - name: Restore dependencies
      working-directory: ./RegistarApi
      run: dotnet restore
      
    

 
    - name: Build
      working-directory: ./RegistarApi
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Tests
      run: dotnet test --no-build --verbosity normal
